[tool.poetry]
name = "mmhdan"
version = "0.1.0"
description = ""
authors = ["Manabu Niseki <manabu.niseki@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
aiodns = "^3.0.0"
aiofiles = "^0.8.0"
asyncwhois = "^1.0.1"
beautifulsoup4 = "^4.11.1"
d8s-urls = "^0.6.0"
fastapi = "^0.109.1"
fastapi-utils = "^0.2.1"
gunicorn = "^22.0.0"
ioc-finder = "^7.2.4"
loguru = "^0.6.0"
mmh3 = "^3.0.0"
pyOpenSSL = "^22.1.0"
requests = {extras = ["security"], version = "^2.32.2"}
tldextract = "^3.4.0"
uvicorn = {extras = ["standard"], version = "^0.20.0"}
whois-parser = "^0.1.4"

[tool.poetry.dev-dependencies]
autoflake = "^1.7"
autopep8 = "^2.0"
black = "^24.3.0"
coveralls = "^3.3.1"
flake8 = "^5.0.4"
isort = "^5.10.1"
mypy = "^0.991"
pre-commit = "^2.20.0"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"
pytest-randomly = "^3.12.0"
pytest-sugar = "^0.9.6"
pyupgrade = "^3.2.2"
vcrpy = "^4.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
